### ISSUE TITLE
JSON export

### ISSUE THREAD

**Issue by ysangkok** [brakowski/poeditor-cli#2]
static-ui is currently relying on JSON output, which has not been implemented yet. A naive version using JSON.stringify in [poeditor-pull.js](https://github.com/brakowski/poeditor-cli/blob/master/poeditor-pull.js#L106) would be ok, but I guess an option to switch output format is needed.

**Comment by brakowski** [comment]
Fixed with commit #ced50e3df36a3a7dfb09e2b63b4404be82cc91f1
